"""Transparency label builder.

Maps a verdict + confidence to the reader-facing label. The three variants are
the verbatim copy from planning.md section 4. Wording is deliberately
non-accusatory on the AI variant and reassuring on the human variant, reflecting
the false-positive asymmetry (a false AI accusation is the worst outcome).
"""

_VARIANTS = {
    "ai": {
        "variant": "ai",
        "title": "Likely AI-generated",
        "body": (
            "Our automated analysis suggests this content was most likely produced "
            "with the help of an AI text generator. This is an estimate, not a "
            "verified fact, and it can be wrong. If you are the creator and believe "
            "this is a mistake, you can appeal and a human will review it."
        ),
    },
    "human": {
        "variant": "human",
        "title": "Likely human-written",
        "body": (
            "Our automated analysis found no strong signs that this content was "
            "generated by AI. It appears to be the creator's own work. This is an "
            "estimate and not a guarantee of authorship."
        ),
    },
    "uncertain": {
        "variant": "uncertain",
        "title": "Origin uncertain",
        "body": (
            "Our automated analysis could not confidently determine whether this "
            "content was written by a person or generated by AI. Please treat its "
            "origin as unverified. If you are the creator, you can appeal to add "
            "context and have a human review it."
        ),
    },
}


def build_label(verdict, confidence):
    """Return the transparency label dict for a verdict, with the confidence
    percentage folded into the title line. Unknown verdicts fall back to the
    uncertain variant (the safest default)."""
    base = _VARIANTS.get(verdict, _VARIANTS["uncertain"])
    confidence_pct = int(round(confidence * 100))
    return {
        "variant": base["variant"],
        "title": base["title"],
        "confidence_pct": confidence_pct,
        "headline": f"{base['title']} - Confidence: {confidence_pct}%",
        "body": base["body"],
    }
